import { ESubProtocol, VBANAudioPacket, VBANPingPacket, VBANSerialPacket, VBANTEXTPacket } from '../../src/index.js';

export const testsPackets = [
    {
        description: 'a ping packet',
        base64Packet:
            'VkJBTmAAAABWQkFOIFNlcnZpY2UAAAAAAwAAACAAAAABAwEAAAAAAAAAAABwFwAAQMQKAEroOQADAQEJAAAAAAAAAAAAAAAAAAAAAGZyLWZyAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAbXktcGMAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAFZCLUF1ZGlvIFNvZnR3YXJlAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABWb2ljZW1lZXRlciBQb3RhdG8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAbXktcGMAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=',
        result: {
            class: VBANPingPacket,
            headers: {
                subProtocol: ESubProtocol.SERVICE,
                streamName: 'VBAN Service',
                sr: 0,
                frameCounter: 3,
                service: 0,
                serviceFunction: 0,
                isReply: false
            }
        }
    },
    {
        description: 'an audio packet (16b/48kHz/2ch)',
        base64Packet:
            'VkJBTgNmAQFTdHJlYW0yAAAAAAAAAAAAmgcAAAABCAEGARABAQEMAQABCgEGARIBEAEdAREBHQELARgBCQEWAQYBEgEJARcBDAEZAQIBDwEAAQ8BCwEYAQoBFwEHARUBFAEgARIBHgEAAQ0B+wAGAfgABQH2AAAB+QABAfYA/gDoAOsA4QDiAOYA5QDiAN0A0gDNAMUAvwDAALkAwAC6AMEAuwDHAMEAygDGAMIAvgC2ALIArgCrAKoApACpAKQAsACpALEApwCtAKQArQCjAKcAngCgAJkAnwCYAJkAlQCOAIsAhgCDAIQAgwCFAIMAfwB9AIEAgACCAIEAcgBxAG0AbQBuAG0AawBrAHUAdgB7AHoAdgB3AHgAeQB9AH0AfQB+AHsAewB8AHsAeAB5AHgAdgB5AHkAdQB3AHIAcgBxAHQAcQBzAG4AbQBjAGUAZgBhAHAAawBvAGoAawBgAGYAXwBgAFcAYQBYAGUAXwBiAFgAXQBWAF8AWgBlAF4AaABiAGYAYQBoAGEAagBkAG4AZQByAGgAcgBqAHQAaQBwAGkAcgBsAHcAcABxAG8AdgBxAHwAeQA=',
        result: {
            class: VBANAudioPacket
        }
    },
    {
        description: 'an audio packet (24b/48kHz/2ch)',
        base64Packet:
            'VkJBTgPuAQJTdHJlYW0yAAAAAAAAAAAAoAkAANIsAF4qAHcuAHMsANotAPQsANYrAHErAPcoAMQoAE8mAAwmAGIkAKskABkkAJQkACMmAPAlAHoqAGkqACUvAJsvAPsvAE8wAIQsAKssAFQoANooAK8mAMUmAFInAHEmANUoAIonABMpAJUnAIAlAJQkAOchALggACkkAMAhABErAGUoAJUvACwtACEtAGYrAFglAEskAM8bAN4aAI0UACETAC8SANEPAAcUAAYRALMWALITAJAVADcTAKYQALgOACkPAGsMAOMSAHAOAEgTAKsNACwOACUIAIYJAH8DABIHAPYBAE8EALv//6sAAEf7/xL//zj5/wUBAAz8/0sFABABABMKADoFAJUNACUIAEwNALcIAO8IAGIFAO4FABgCAPQFAAECACQFAHUBAKcBAGL9///9/+/4/xD+/8L4/x8AAJv7//j//wz8/5b7/0H4/9f1/1r0/wD0/9Pz/zj0/+b0/4Ly/4rz/9ft/87u/+rp/7Hr/wXs/yXu/wXx/8Dy/8jz/4H0/7b1/yD2/3L6/177/yoAAH4AABoDAPMCAAMDACkCAAgAACn//1/+/9r+/9z//+4AAF/+/wMAAJ/6/8v8/zX9/zT//xcHANwHAOUOAMINAHAOAEoMAEYIAGQGAG4DAO0CAKgEAFoEAHMIAJYGADMMAK4JAAgSAF0QAFwXAJ0WABUYAFEXAGoWABQVAAsWAG8TALMWABUTAMEXAMsUADwYALMWACQXAKwVABgXALgTANYZAKYVAJ0bAMMYAGAZAIkXAFQWAL4TAJUVAAARAEQUAEUPAPYOADYLAHwHAB4FADwDADkCAGMDAMYCAAgFAIcEAOgFADcGANsEAJQFAGUEAFoEAF0IALIGANgNAPMKANgNAPkKAKIJAPAGAJUIAP0EAPEJAFYFAMgIANkDACAGAOsBABsGALEDAHMIAFsHABwJALUHAAUJAJEGAGMLACcJAA4NAEoMAAIKAIMKACcEAOEEAOD+/7j+/w/7/w36/zr6/5v4/8v8/xr7/wgAAKj+/5wBAFcAAFcAAG0AAP7//6cBAOYEADMHAIwJALILACMHAG4IALgBAFACAFv//yP//2j9/wP9/3/7/xf8/839/7P+/x3//wf//037/wL6/wP4/9f1/4X2/3D0/0D1/+b0/zz2/6T3/1X3/775/6zz/+r2/6Tt/9Lw/wPr/9zt/0Hr/9Pu/0rq/z7v/7nn//bs/xzn/1fr/6jn/xnr/x7j/yXm/9fb/wXf/+ba/3ne/6jf/xnj/5rj/xzn///j/yno/9rf/5zk/5XZ/8Xd/xvX/1/a/xrZ/1jc/zLa/4Te/13Z/07f/4ba/2Ph/3bd/63k/3ne/1vl/03c/2Xi/53a/4jg/4bf/1vl//Po/6zu/+/r/77x//Xm/w3t/zHk/9Dq/+Tm/33t/wHq/+zv/3Tu/yvz/3b0/5X4/6bz/+33/w7w/1jz/0z9/4j//6wVAN0XAP4UAFwXAHn4/+36/53s/+ru/5oAALMBACkPAO4NAHIFAEwDAOH8/5b7/+0CAG8BAB0HAAYEANMDAJ///8cFADQCAKEQACcOAJoXAEEVADQPAPALACT9/xD5/1vy/9nu/931/4Tz//b+//T9/0EIALcIAOMSAOsTAOUTANwUAAH//+3//2jm/wvn/+zq/57q/58FAPUDAIYOADwLAIj//4X7/6/3/w31/8v8/yj8/3v5/675/wLt/6Tt/67n/4Dp/zjs/8Pu//Xu/8nx/1bo//Tr/2nh/1Xl/2bl/47o/27u/7/v/83w/7jx/87u/9jw/0fu/+nw/+fq/6Hu/6Lk/wrp/w7j//fn/0vo/7Xt/0Hu/8Lz/8zt/8jz/47o/6js/yPl/yHn/6jn/1Pp/4ru/0bw/1Dy/9L1/+zv/1r0/3Pr/3zv/w==',
        result: {
            class: VBANAudioPacket
        }
    },
    {
        description: 'an audio packet (16b/48kHz/8ch)',
        base64Packet:
            'VkJBTgNYBwFTdHJlYW0yAAAAAAAAAAAA8QkAAPz//P8AAAAAAAAAAAAAAAD8//z/AAAAAAAAAAAAAAAA/P/8/wAAAAAAAAAAAAAAAPz//P8AAAAAAAAAAAAAAAD8//z/AAAAAAAAAAAAAAAA/P/8/wAAAAAAAAAAAAAAAPz//f8AAAAAAAAAAAAAAAD8//3/AAAAAAAAAAAAAAAA/f/9/wAAAAAAAAAAAAAAAP3//v8AAAAAAAAAAAAAAAD9//7/AAAAAAAAAAAAAAAA/f/+/wAAAAAAAAAAAAAAAP7//v8AAAAAAAAAAAAAAAD+//7/AAAAAAAAAAAAAAAA/v/+/wAAAAAAAAAAAAAAAP7//v8AAAAAAAAAAAAAAAD+//7/AAAAAAAAAAAAAAAA/v/+/wAAAAAAAAAAAAAAAP3//v8AAAAAAAAAAAAAAAD+//7/AAAAAAAAAAAAAAAA/v/+/wAAAAAAAAAAAAAAAP7//v8AAAAAAAAAAAAAAAD+////AAAAAAAAAAAAAAAA/v///wAAAAAAAAAAAAAAAP7///8AAAAAAAAAAAAAAAD+////AAAAAAAAAAAAAAAA/v///wAAAAAAAAAAAAAAAP7///8AAAAAAAAAAAAAAAD+//7/AAAAAAAAAAAAAAAA/v/+/wAAAAAAAAAAAAAAAP7//v8AAAAAAAAAAAAAAAD9//7/AAAAAAAAAAAAAAAA/f/+/wAAAAAAAAAAAAAAAP3//v8AAAAAAAAAAAAAAAD9//3/AAAAAAAAAAAAAAAA/f/9/wAAAAAAAAAAAAAAAP3//f8AAAAAAAAAAAAAAAD9//3/AAAAAAAAAAAAAAAA/f/9/wAAAAAAAAAAAAAAAP3//f8AAAAAAAAAAAAAAAD9//3/AAAAAAAAAAAAAAAA/f/9/wAAAAAAAAAAAAAAAP3//f8AAAAAAAAAAAAAAAD9//3/AAAAAAAAAAAAAAAA/f/9/wAAAAAAAAAAAAAAAP3//f8AAAAAAAAAAAAAAAD9//3/AAAAAAAAAAAAAAAA/f/9/wAAAAAAAAAAAAAAAP3//f8AAAAAAAAAAAAAAAD9//7/AAAAAAAAAAAAAAAA/v///wAAAAAAAAAAAAAAAP////8AAAAAAAAAAAAAAAD//wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD//wAAAAAAAAAAAAAAAAAA//8AAAAAAAAAAAAAAAAAAP//AAAAAAAAAAAAAAAAAAD//wAAAAAAAAAAAAAAAAAA//8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA//8AAAAAAAAAAAAAAAAAAP//AAAAAAAAAAAAAAAAAAD//wAAAAAAAAAAAAAAAAAA//8AAAAAAAAAAAAAAAAAAP////8AAAAAAAAAAAAAAAD/////AAAAAAAAAAAAAAAA/v///wAAAAAAAAAAAAAAAP7///8AAAAAAAAAAAAAAAD+////AAAAAAAAAAAAAAAA/v///wAAAAAAAAAAAAAAAP////8AAAAAAAAAAAAAAAD/////AAAAAAAAAAAAAAAA/////wAAAAAAAAAAAAAAAP//AAAAAAAAAAAAAAAAAAD//wAAAAAAAAAAAAAAAAAA//8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAABAAEAAAAAAAAAAAAAAAAAAQACAAAAAAAAAAAAAAAAAAEAAgAAAAAAAAAAAAAAAAABAAIAAAAAAAAAAAAAAAAAAQACAAAAAAAAAAAAAAAAAAEAAgAAAAAAAAAAAAAAAAABAAIAAAAAAAAAAAAAAAAA',
        result: {
            class: VBANAudioPacket
        }
    },
    {
        description: 'an audio packet (24b/96kHz/8ch)',
        base64Packet:
            'VkJBTgQ6BwJTdHJlYW0yAAAAAAAAAAAAoAoAAHen/6DE/wAAAAAAAAAAAAAAAAAAAAAAAHen/6DE/wAAAAAAAAAAAAAAAAAAAAAAAKa6/0nV/wAAAAAAAAAAAAAAAAAAAAAAAKa6/0nV/wAAAAAAAAAAAAAAAAAAAAAAAIHN/3/m/wAAAAAAAAAAAAAAAAAAAAAAAIHN/3/m/wAAAAAAAAAAAAAAAAAAAAAAAMXY/5Hx/wAAAAAAAAAAAAAAAAAAAAAAAMXY/5Hx/wAAAAAAAAAAAAAAAAAAAAAAAKzc/6H2/wAAAAAAAAAAAAAAAAAAAAAAAKzc/6H2/wAAAAAAAAAAAAAAAAAAAAAAANfg/1T5/wAAAAAAAAAAAAAAAAAAAAAAANfg/1T5/wAAAAAAAAAAAAAAAAAAAAAAACfi//P1/wAAAAAAAAAAAAAAAAAAAAAAACfi//P1/wAAAAAAAAAAAAAAAAAAAAAAAB/Z/4fq/wAAAAAAAAAAAAAAAAAAAAAAAB/Z/4fq/wAAAAAAAAAAAAAAAAAAAAAAABTM/37e/wAAAAAAAAAAAAAAAAAAAAAAABTM/37e/wAAAAAAAAAAAAAAAAAAAAAAAO/C/2PU/wAAAAAAAAAAAAAAAAAAAAAAAO/C/2PU/wAAAAAAAAAAAAAAAAAAAAAAADi2/8rD/wAAAAAAAAAAAAAAAAAAAAAAADi2/8rD/wAAAAAAAAAAAAAAAAAAAAAAAIqb/2qm/wAAAAAAAAAAAAAAAAAAAAAAAIqb/2qm/wAAAAAAAAAAAAAAAAAAAAAAACp0/wh+/wAAAAAAAAAAAAAAAAAAAAAAACp0/wh+/wAAAAAAAAAAAAAAAAAAAAAAAEZI/3VR/wAAAAAAAAAAAAAAAAAAAAAAAEZI/3VR/wAAAAAAAAAAAAAAAAAAAAAAABAd/0gl/wAAAAAAAAAAAAAAAAAAAAAAABAd/0gl/wAAAAAAAAAAAAAAAAAAAAAAAN3w/rr3/gAAAAAAAAAAAAAAAAAAAAAAAN3w/rr3/gAAAAAAAAAAAAAAAAAAAAAAAIvA/vbF/gAAAAAAAAAAAAAAAAAAAAAAAIvA/vbF/gAAAAAAAAAAAAAAAAAAAAAAAE2M/hCP/gAAAAAAAAAAAAAAAAAAAAAAAE2M/hCP/gAAAAAAAAAAAAAAAAAAAAAAAItW/k5W/gAAAAAAAAAAAAAAAAAAAAAAAItW/k5W/gAAAAAAAAAAAAAAAAAAAAAAAHkk/ksh/gAAAAAAAAAAAAAAAAAAAAAAAHkk/ksh/gAAAAAAAAAAAAAAAAAAAAAAAGb6/dzy/QAAAAAAAAAAAAAAAAAAAAAAAGb6/dzy/QAAAAAAAAAAAAAAAAAAAAAAAMLZ/e3O/QAAAAAAAAAAAAAAAAAAAAAAAMLZ/e3O/QAAAAAAAAAAAAAAAAAAAAAAAG3E/aq3/QAAAAAAAAAAAAAAAAAAAAAAAG3E/aq3/QAAAAAAAAAAAAAAAAAAAAAAADG4/SWo/QAAAAAAAAAAAAAAAAAAAAAAADG4/SWo/QAAAAAAAAAAAAAAAAAAAAAAAN6w/Wed/QAAAAAAAAAAAAAAAAAAAAAAAN6w/Wed/QAAAAAAAAAAAAAAAAAAAAAAAPex/SGc/QAAAAAAAAAAAAAAAAAAAAAAAPex/SGc/QAAAAAAAAAAAAAAAAAAAAAAAMW+/WKo/QAAAAAAAAAAAAAAAAAAAAAAAMW+/WKo/QAAAAAAAAAAAAAAAAAAAAAAAMzR/dW7/QAAAAAAAAAAAAAAAAAAAAAAAMzR/dW7/QAAAAAAAAAAAAAAAAAAAAAAACno/V/Q/QAAAAAAAAAAAAAAAAAAAAAAACno/V/Q/QAAAAAAAAAAAAAAAAAAAAAAAOQI/jTt/QAAAAAAAAAAAAAAAAAAAAAAAA==',
        result: {
            class: VBANAudioPacket
        }
    },
    {
        description: 'a serial packet (MIDI/115200bps/B06B00)',
        base64Packet: 'VkJBTi4AAABDb21tYW5kMQAAAAAAAAAAIAAAALBrAA==',
        result: {
            class: VBANSerialPacket
        }
    },
    {
        description: 'a text packet (test;)',
        base64Packet: 'VkJBTlIAABBDb21tYW5kMQAAAAAAAAAAAgAAAHRlc3Q7',
        result: {
            class: VBANTEXTPacket
        }
    },
    {
        description: 'a text packet (utf-8)',
        base64Packet: 'VkJBTlIAABBDb21tYW5kMQAAAAAAAAAAAwAAAFZCQU4tVGVzdCDDqcOgw6fCp/CfpJQ7',
        result: {
            class: VBANTEXTPacket
        }
    },
    {
        description: 'a text packet (short streamName)',
        base64Packet: 'VkJBTlIAABBhAAAAAAAAAAAAAAAAAAAAAQAAAGE7',
        result: {
            class: VBANTEXTPacket
        }
    },
    {
        description: 'a text packet (long streamName)',
        base64Packet: 'VkJBTlIAABAwMTIzNDU2Nzg5MDEyMzQ1AAAAAGE7',
        result: {
            class: VBANTEXTPacket
        }
    }
];
