export enum ECodecs {
    VBAN_CODEC_PCM = 0x00,
    VBAN_CODEC_VBCA = 0x10, //VB-AUDIO AOIP CODEC
    VBAN_CODEC_VBCV = 0x20, //VB-AUDIO VOIP CODEC
    VBAN_CODEC_UNDEFINED_1 = 0x30,
    VBAN_CODEC_UNDEFINED_2 = 0x40,
    VBAN_CODEC_UNDEFINED_3 = 0x50,
    VBAN_CODEC_UNDEFINED_4 = 0x60,
    VBAN_CODEC_UNDEFINED_5 = 0x70,
    VBAN_CODEC_UNDEFINED_6 = 0x80,
    VBAN_CODEC_UNDEFINED_7 = 0x90,
    VBAN_CODEC_UNDEFINED_8 = 0xa0,
    VBAN_CODEC_UNDEFINED_9 = 0xb0,
    VBAN_CODEC_UNDEFINED_10 = 0xc0,
    VBAN_CODEC_UNDEFINED_11 = 0xd0,
    VBAN_CODEC_UNDEFINED_12 = 0xe0,
    VBAN_CODEC_USER = 0xf0
}